keys:
  - &laptop age1xcmezhqgn33mjqxh426f7ccwnm8zh5vs7k4sqr076kv364l4w3eqs9y847
  - &server age1mev8ac870uyxj3xxqpvx7lgs573k59kdkxgv6sgdzuqfawxzk9uqq0mm2u
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *laptop
      - *server

